import {test} from 'node:test';
import assert from 'node:assert/strict';
import {seed,assess,advance,requestConfirmation,receiveReply,verifyNearby,recommendation,shortAnswer} from '../lib/engine.ts';
test('nearest stale point is not recommended',()=>{const w=seed();assert.equal(assess(w,w.points[0]).status,'stale');assert.equal(recommendation(w)?.point.id,'p2');});
test('newer resident contradiction blocks caretaker availability',()=>{const w=seed();assert.equal(assess(w,w.points[2]).status,'conflict');});
test('report that expires on the journey is not eligible',()=>{const w=seed();assert.equal(assess(w,w.points[4]).eligible,false);});
test('resident-only report is not verified',()=>{const w=seed();assert.equal(assess(w,w.points[6]).status,'unknown');});
test('verification requests only closer uncertain points',()=>{const w=verifyNearby(seed());assert.deepEqual(w.requests.map(r=>r.pointId),['p1','p3','p7']);});
test('pending requests are deduplicated',()=>{const w=requestConfirmation(seed(),'p1');assert.equal(requestConfirmation(w,'p1').requests.length,1);});
test('opt-out blocks even a direct request',()=>assert.throws(()=>requestConfirmation(seed(),'p10'),/opt-in/));
test('unknown identifiers rejected',()=>assert.throws(()=>requestConfirmation(seed(),'p99'),/Unknown/));
test('fresh evidence prevents unnecessary messaging',()=>assert.throws(()=>requestConfirmation(seed(),'p2'),/No request needed/));
test('three-message budget enforced',()=>assert.throws(()=>requestConfirmation(verifyNearby(seed()),'p6'),/budget/));
test('fresh reply changes recommendation',()=>{const w=receiveReply(requestConfirmation(seed(),'p1'),'q1','operating',4,'Operating now. Queue 4 minutes.');assert.equal(recommendation(w)?.point.id,'p1');});
test('closed reply never becomes operating',()=>{const w=receiveReply(requestConfirmation(seed(),'p1'),'q1','not_operating',null,'Dry. Not operating.');assert.equal(assess(w,w.points[0]).status,'closed');});
test('ambiguous reply remains unknown',()=>{const w=receiveReply(requestConfirmation(seed(),'p1'),'q1','unknown',null,'Maybe later.');assert.equal(assess(w,w.points[0]).status,'unknown');});
test('same-time conflicting report is conservatively unresolved',()=>{let w=requestConfirmation(seed(),'p3');w.reports.push({id:'extra',pointId:'p3',source:'resident',status:'not_operating',at:0,queue:null,text:'Dry.'});w=receiveReply(w,'q1','operating',null,'Operating.');assert.equal(assess(w,w.points[2]).status,'conflict');});
test('newer caretaker reply resolves older conflict',()=>{const w=receiveReply(requestConfirmation(seed(),'p3'),'q1','operating',2,'Operating now.');assert.equal(assess(w,w.points[2]).status,'verified');});
test('request times out at boundary without fabricating a reply',()=>{const w=advance(requestConfirmation(seed(),'p1'),15);assert.equal(w.requests[0].state,'timed_out');assert.equal(w.reports.length,10);});
test('late reply rejected',()=>assert.throws(()=>receiveReply(advance(requestConfirmation(seed(),'p1'),15),'q1','operating',0,'Operating'),/pending/));
test('reply replay rejected',()=>{const w=receiveReply(requestConfirmation(seed(),'p1'),'q1','operating',0,'Operating');assert.throws(()=>receiveReply(w,'q1','operating',0,'Operating'),/pending/);});
test('invalid queue rejected',()=>assert.throws(()=>receiveReply(requestConfirmation(seed(),'p1'),'q1','operating',-1,'Operating'),/Queue/));
test('all evidence expires',()=>{const w=advance(seed(),60);assert.equal(recommendation(w),null);assert.match(shortAnswer(w),/No location/);});
test('future report ignored',()=>{const w=seed();w.reports.push({id:'future',pointId:'p1',source:'caretaker',status:'operating',at:10,queue:0,text:'Future'});assert.equal(assess(w,w.points[0]).status,'stale');});
test('engine does not mutate the caller state',()=>{const w=seed();verifyNearby(w);assert.equal(w.requests.length,0);assert.equal(w.audit.length,1);});
test('travel freshness is exclusive at exact expiry',()=>{const w=seed();w.reports.find(r=>r.pointId==='p2')!.at=-42;assert.equal(assess(w,w.points[1]).eligible,false);});
test('large and negative time jumps rejected',()=>{assert.throws(()=>advance(seed(),-1));assert.throws(()=>advance(seed(),121));});
