'use client';
import {useEffect,useRef,useState} from 'react';
import {Droplets,Clock3,ArrowRight,RotateCcw,MessageCircle,Footprints,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {seed,ranked,recommendation,verifyNearby,requestConfirmation,receiveReply,advance,shortAnswer,type World,type Availability} from '@/lib/engine';
const labels={verified:'Reported operating',closed:'Reported closed',stale:'Report expired',conflict:'Reports disagree',unknown:'Unconfirmed'};
type Evidence={started:string;model:string;durationMs:number;trace:{tool:string;input:unknown;output:unknown}[];answer:string};
export default function Home(){
 const [world,setWorld]=useState<World>(seed),[notice,setNotice]=useState(''),[status,setStatus]=useState<Availability>('operating'),[queue,setQueue]=useState('4'),[evidence,setEvidence]=useState<Evidence|null>(null),[error,setError]=useState('');
 const ref=useRef(world);ref.current=world;
 const best=recommendation(world),pending=world.requests.filter(r=>r.state==='pending');
 function apply(fn:(w:World)=>World,message:string){try{const n=fn(ref.current);ref.current=n;setWorld(n);setNotice(message);}catch(e){setNotice(e instanceof Error?e.message:'Action failed.');}}
 function reply(id:string){const q=queue.trim()===''?null:Number(queue);const text=status==='operating'?`Operating now.${q===null?'':` Queue ${q} minutes.`}`:status==='not_operating'?'Not operating. The pump is dry.':'I cannot confirm whether it is working.';apply(w=>receiveReply(w,id,status,q,text),'Simulated reply recorded. Recommendation recalculated.');}
 async function loadEvidence(){setError('');try{const r=await fetch('/evidence/strands-run.json');if(!r.ok)throw Error('Execution evidence is not available yet.');setEvidence(await r.json());}catch(e){setError(e instanceof Error?e.message:'Could not load evidence.');}}
 function download(){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(world,null,2)],{type:'application/json'}));a.href=url;a.download='before-you-walk-simulation.json';a.click();URL.revokeObjectURL(url);}
 useEffect(()=>{
  type MC={registerTool:(t:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},o:{signal:AbortSignal})=>unknown};
  const mc=(document as Document&{modelContext?:MC}).modelContext;if(!mc)return;const lifecycle=new AbortController();
  const tools=[{name:'read_water_demo',description:'Read this fictional simulation. Not real water availability.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(i:unknown)=>{if(!i||typeof i!=='object'||Object.keys(i).length)throw Error('Expected empty object');return {minute:ref.current.now,answer:shortAnswer(ref.current),requests:ref.current.requests};}},{name:'request_demo_confirmation',description:'Create a request in the page-local FICTIONAL caretaker inbox only. No real message is sent.',inputSchema:{type:'object',properties:{pointId:{type:'string'}},required:['pointId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(i:unknown)=>{const v=i as {pointId?:unknown};if(!v||typeof v.pointId!=='string'||Object.keys(v).length!==1)throw Error('Expected pointId string');const n=requestConfirmation(ref.current,v.pointId);ref.current=n;setWorld(n);setNotice('Simulated request created through WebMCP.');await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {requests:n.requests};}}];
  for(const t of tools)try{Promise.resolve(mc.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{/* optional browser API */}return()=>lifecycle.abort();
 },[]);
 return <main className="walk-app"><header className="mast"><a href="/" className="brand"><Droplets/> Before You Walk</a><span className="simulation">Demo · No real messages</span></header>
 <section className="intro compact"><div><h1>Water point reports</h1><p>Check availability before heading out.</p></div><div className="clock"><Clock3/><span>Simulation clock<strong>+{world.now} min</strong></span><Button variant="outline" onClick={()=>apply(w=>advance(w,15),'15 simulated minutes elapsed.')} aria-label="Advance simulation by 15 minutes">+15 min</Button></div></section>
 <div className="disclosure"><strong>Try the demo</strong> · This page runs the decision rules locally. For the model-driven workflow, see the separate Strands agent below. <a href="#agent-evidence" onClick={loadEvidence}>View recorded run ↓</a></div>
 <section className="workspace"><article className="panel"><div className="section-heading"><h2>Your next collection</h2><Footprints size={22}/></div><div className={`recommendation ${best?'':'uncertain'}`}><span className="eyebrow">{best?'Closest confirmed option':'Waiting for confirmation'}</span><h3>{best?.point.name??'No reliable option yet'}</h3><p>{best?`${best.point.walk}-minute estimated walk · caretaker report ${world.now-best.latest!.at} minutes old`:'No caretaker report remains fresh through estimated arrival.'}</p><p className="answer">{best?'Reported operating, not guaranteed. Check again if departure is delayed.':'Old or conflicting reports do not establish current availability.'}</p>{best?.latest&&best.latest.queue!==null&&<p className="fine">Reported queue: {best.latest.queue} minutes. Not included in walking estimates.</p>}</div><Button className="action" onClick={()=>apply(verifyNearby,'Nearby uncertain points checked. New requests appear in the caretaker inbox.')}><MessageCircle/> Check closer options <ArrowRight/></Button><p className="fine muted">Opt-in only. Duplicate requests suppressed. Maximum three requests per session.</p><p className="notice" role="status">{notice||'Check closer options, then simulate a caretaker reply in the inbox.'}</p></article>
 <aside className="panel session-notes"><h2>About these reports</h2><p>Reports last 60 minutes and must stay fresh through the estimated walk. If reports disagree, confirmation is needed.</p><div className="statline"><strong>{world.requests.length}/3</strong><span>simulated requests used</span></div><p className="fine">Availability does not establish water quality or safety. Names, distances, reports, and replies are fictional. No field impact has been measured.</p></aside></section>
 <Tabs defaultValue="points" className="details-tabs"><TabsList><TabsTrigger value="points">Water points · 10</TabsTrigger><TabsTrigger value="inbox">Caretaker inbox · {pending.length}</TabsTrigger><TabsTrigger value="audit">Audit trail · {world.audit.length}</TabsTrigger></TabsList>
 <TabsContent value="points"><div className="point-grid">{ranked(world).map(a=><article className="point" key={a.point.id}><div className="section-heading"><h3>{a.point.name}</h3><span className="walk"><Footprints size={15}/>{a.point.walk} min</span></div><span className={`badge ${a.status}`}>{labels[a.status]}</span><p>{a.reason}</p><p className="fine muted">{a.latest?`${a.latest.source} · ${world.now-a.latest.at} min ago · evidence ${a.latest.id}`:'No evidence yet'}{!a.point.consent?' · not opted in':''}</p><Button variant="outline" disabled={a.eligible||!a.point.consent||world.requests.length>=3||pending.some(r=>r.pointId===a.point.id)} onClick={()=>apply(w=>requestConfirmation(w,a.point.id),`Simulated request created for ${a.point.name}.`)}>Request confirmation</Button></article>)}</div></TabsContent>
 <TabsContent value="inbox"><section className="panel inbox"><h2>Play the caretaker in this simulation</h2><p>These controls create fictional replies. They are not connected to SMS, WhatsApp, or real caretakers. Production use would need authenticated, opted-in channels.</p><div className="reply-controls"><label>Reply status<Select value={status} onValueChange={v=>v&&setStatus(v as Availability)}><SelectTrigger aria-label="Simulated reply status"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="operating">Operating now</SelectItem><SelectItem value="not_operating">Not operating</SelectItem><SelectItem value="unknown">Cannot confirm</SelectItem></SelectContent></Select></label><label>Queue minutes (optional)<input aria-label="Queue minutes" type="number" min="0" max="240" value={queue} onChange={e=>setQueue(e.target.value)} disabled={status!=='operating'}/></label></div>{!pending.length?<p className="empty">No pending requests. Check closer options to begin, or reset after using the request budget.</p>:pending.map(r=><div className="inbox-item" key={r.id}><div><strong>{world.points.find(p=>p.id===r.pointId)?.name}</strong><p>{r.text}</p><small>{r.id} · expires in {15-(world.now-r.at)} simulated minutes</small></div><Button className="action" onClick={()=>reply(r.id)}>Simulate reply</Button></div>)}</section></TabsContent>
 <TabsContent value="audit"><section className="panel"><div className="section-heading"><h2>Decision history</h2><Button variant="outline" onClick={download}><Download/> Export</Button></div><ol className="timeline">{[...world.audit].reverse().map((e,i)=><li key={i}><time>+{e.at} min</time><div><strong>{e.action}</strong><p>{e.detail}</p></div></li>)}</ol></section></TabsContent></Tabs>
 <section id="agent-evidence" className="panel evidence"><div className="section-heading"><h2>Strands agent run</h2><Button variant="outline" onClick={loadEvidence}>Load recorded execution</Button></div><p>The source includes five Strands tools: inspect evidence, request confirmation, read a reply, record a grounded interpretation, and return a policy-checked answer. A local model orchestrates them; policy enforces consent, freshness, and message limits.</p><p className="fine muted">This is a recording of a real model run, not a live model call. Local inference uses Ollama. Amazon Bedrock is an optional configuration, not claimed as tested.</p>{error&&<p role="alert">{error}</p>}{evidence&&<div><div className="evidence-meta"><span>{evidence.model}</span><span>{Math.round(evidence.durationMs/1000)} seconds</span><span>{evidence.trace.length} tool events</span><span>{new Date(evidence.started).toLocaleString()}</span></div><ol className="timeline">{evidence.trace.map((e,i)=><li key={i}><time>{i+1}</time><div><strong>{e.tool.replaceAll('_',' ')}</strong><pre>{JSON.stringify({input:e.input,output:e.output},null,2)}</pre></div></li>)}</ol><p>{evidence.answer}</p></div>}<a href="/evidence/strands-run.json">Execution JSON</a> · <a href="/architecture.svg">Architecture diagram</a></section>
 <footer><span>Before You Walk · James Thannickal · <a href="https://github.com/jthannickal/before-you-walk#credits">Credits</a></span><Button variant="ghost" onClick={()=>{const n=seed();ref.current=n;setWorld(n);setNotice('Simulation reset.');}}><RotateCcw/> Reset simulation</Button></footer></main>;
}
